# Site settings
title: Wendy Smoak
email: wsmoak@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wsmoak.net" # the base hostname & protocol for your site
twitter_username: wsmoak
github_username:  wsmoak

# Build settings
markdown: kramdown
